<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.13.0" />
    <PackageReference Include="Docker.DotNet" Version="3.125.15" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
    <PackageReference Include="Hangfire.InMemory" Version="1.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DockerContainerUpdateChecker.Tests\**\*.cs" />
    <EmbeddedResource Remove="DockerContainerUpdateChecker.Tests\**\*" />
    <None Remove="DockerContainerUpdateChecker.Tests\**\*" />
  </ItemGroup>

</Project>
